# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: organization
    label: Organization
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: notes
    label: Description
    form_template: form/textarea.html
    datajson: description
  - field_name: license
    label: License
    form_template: form/license.html
    datajson: license
  - field_name: category
    label: Category
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: type
    label: Resource Type
    datajson: type
  - field_name: maintainer
    label: Maintainer
    datajson: contactPoint.fn
  - field_name: maintainer_email
    label: Maintainer Email
    datajson: contactPoint.hasEmail
  - field_name: creator
    label: Creator
    datajson: creator
  - field_name: creator_email
    label: Creator Email
    datajson: creator_email
  - field_name: publisher
    label: Publisher
    datajson: publisher
  - field_name: owner
    label: Owner
    datajson: owner
  - field_name: validator
    label: Validator
    datajson: validator
  - field_name: keyword
    label: Keyword
    datajson: keyword
  - field_name: domain
    label: Domain
    datajson: domain
  - field_name: language
    label: Language
    datajson: language
  - field_name: min_longitude
    label: Min Longitude
    datajson: min_longitude
  - field_name: max_longitude
    label: Max Longitude
    datajson: max_longitude
  - field_name: min_latitude
    label: Min Latitude
    datajson: min_latitude
  - field_name: max_latitude
    label: Max Latitude
    datajson: max_latitude
  - field_name: temporal_extent
    label: Temporal Extent
    datajson: temporal_extent
  - field_name: generating_activity
    label: Generating Activity
    datajson: generating_activity


resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - rdf
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - zip
  - field_name: reference_ontology
    label: Reference Ontology
    datajson: distribution.reference_ontology
  - field_name: reference_original_dataset
    label: Reference Original Dataset
    datajson: distribution.reference_original_dataset
  - field_name: reference_domain_language
    label: Reference Domain Language
    datajson: distribution.reference_domain_language
  - field_name: size
    label: Size
    datajson: distribution.size
  - field_name: issue_datetime
    label: Issue Date Time
    datajson: issue_datetime
  - field_name: modification_datetime
    label: Modification Date Time
    datajson: modification_datetime
  - field_name: note
    label: Note
    datajson: distribution.note

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html

type_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo